// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVCKMmJFrwD0cAp_NlskcUNM4d66dvH-Y',
    appId: '1:138939647082:web:f7c0355453d9b242f73613',
    messagingSenderId: '138939647082',
    projectId: 'social-23800',
    authDomain: 'social-23800.firebaseapp.com',
    storageBucket: 'social-23800.appspot.com',
    measurementId: 'G-3BDKKEE4MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD38Sjrib8YP95mpSZi376Qw81mBg__Fpc',
    appId: '1:138939647082:android:e83cc6e45900e3e6f73613',
    messagingSenderId: '138939647082',
    projectId: 'social-23800',
    storageBucket: 'social-23800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjHl4_UW6cSBca1W0h24av6RxarBwA9jE',
    appId: '1:138939647082:ios:35b567e3cb2c7a10f73613',
    messagingSenderId: '138939647082',
    projectId: 'social-23800',
    storageBucket: 'social-23800.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjHl4_UW6cSBca1W0h24av6RxarBwA9jE',
    appId: '1:138939647082:ios:0f563688820f59cff73613',
    messagingSenderId: '138939647082',
    projectId: 'social-23800',
    storageBucket: 'social-23800.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
